### ISSUE TITLE
Port AutoKey-Qt to pure Qt4

### ISSUE THREAD

**Issue by luziferius** [luziferius/autokey#10]
# TODO
Things currently missing, broken or otherwise non-functional in the all-new, shiny, Qt4-only main window:
## Application
- [x] - The Application does not react to right-clicking the tray icon after closing the main window.
- [x] - Sometimes [Ctrl]+[C] in the terminal window is caught properly, but most of the time, AutoKey is killed by this.
- [x] - Configuration storage location: Move the config out of `.kde` folder, because AutoKey is not a KDE application anymore. Only the KXMLGUI configuration was there, all code occurrences deleted.
- [x] - Specify all new packages in setup.py
- [x] - Removed leftover config files (KXMLGUI)
- [ ] - Removed all mentions of KDE, KDE4, PyKDE, PyKDE4 (Any left?)
- [x] - Fix all keyboard shortcuts, by using `QKeySequence::StandardKey` enum values. This is unsupported by QtDesigner, so do it in code.
### Help
- [x] - AboutQt dialog
- [x] - About AutoKey dialog
### Settings
- [x] - show toolbar switch; Partially implemented: functional, but state is not saved.
- [x] - Configure shortcuts. Wontfix? This was part of the KXmlGui functionality.
- [x] - Configure toolbar. Wontfix? This was part of the KXmlGui functionality.
- [x] - Maybe hide both configuration items?
### Tools
- [ ] - Record script, did this even work before? 

## Toolbar
- [x] - Add a Menu toolbar button containing a dropdown with new folder, new subfolder, new script and new phrase. Old interface had this functionality, but Qt Designer does not support this, so add this in code.
## Tree view
- [x] - Restore the custom context menu. Fully restored, but now contains a different, bigger set of actions.
## Log view
- [x] - Restore the custom context menu.

## Popup menu
- [x] Fixed, now even better than before: Each action/item has an appropriate icon.
## Tray Icon / context menu
- [x] Redesigned, now with 90% less object destructions/re-creations.
